baseurl: /architecture
dataset-graph-url: http://s3.amazonaws.com/spacetime-nypl-org/datasets/data-dependencies/spacetime-graph.svg
interactive-architecture-url: http://spacetime.nypl.org/interactive-architecture/
